### ISSUE TITLE
Send a Bid - Process

### ISSUE THREAD

**Issue by design8** [SmartCash/busybee#1]
**Smart Tasks page:**
1. Tasks need links to the project, task card and issue on github.

**Send a Bid pop up screen:**
2. Password: This was confusing to me because I haven't created a pass yet, and didn't see any options to create an account.
4. Phone field: What do you need my phone number for? A description of why this is needed might be helpful to cautious users. 
5. Deadline Field: Maybe change to "Expected Deadline" or "Expected Timing".

**Bid Activation Link page:**
6. After entering in my password (assuming I created this password when bidding), it gave me a pop up notification that my bid was successfully submitted, but then did not redirect me anywhere. I was stuck on the Activate page.
    - maybe have it redirect to the home page or bids page
7. Then, clicking on the BusyBee logo at this point took me to the Create a Task page /getToken.html
    - I assume it should go to the home /index.html page to get out of being stuck on the activation page.

**General**
8. It would be nice to be able to see what bids I have submitted.

**Comment by enriquesouza** [comment]
Great! I will review these steps to make sure it works fine.

**Comment by enriquesouza** [comment]
Password is now with labels and placeholders;

Deadline: Well, we usually say how many days we expect a task to be done. So for example, if I know the guy could do it in 1 day I would say I expect it to be done in one day, but when they BID they can say they can do it in 2 days.
So after approved we expect it to be delivered in 2 days.

BID Activation:
I've changed the logo URL;
If successful activation I redirect the user to busy bee home;

Bid review. I could send it all to your email so you can activate it or not.
